### PR TITLE
Example alignment

### PR DESCRIPTION
**Pull request by jseppi**
Cleanup example JSON with consistent indentation and formatting

### CODE REVIEW

**Comment by sgillies** [comment]
@jseppi I'm always in favor of clearer examples, but text formatting is so much a matter of taste... what would you think about committing the output of some well known tool (say, Python's `json.dump` or `JSON.stringify()`) instead of hand-written?

**Comment by jseppi** [comment]
Sure, will do.

**Comment by jseppi** [comment]
I used `JSON.stringify(example, null, 2)` on all the examples, but am not sure this has improved them.
The coordinate arrays are now expanded to multiple lines, and because ordering or properties is not guaranteed the examples might not be highlighting what they should be.

Open to other suggestions.

**Comment by sgillies** [comment]
Closing. Examples are fixed in RFC 7946.

**Pull request closed without merging**
